In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/curated/data_half_year.csv")

In [4]:
df

,user_id,merchant_abn,dollar_value,order_datetime,state,postcode,gender,consumer_id,name_y,tags,...,2011-2021%,Area,Population density 2021,Earners (persons)2017-18,Median age of earners (years)2017-18,Sum ($)2017-18,Median ($)2017-18,Mean ($)2017-18,fraud_probability_x,fraud_probability_y
0,11138,89726005175,47.782122,2022-04-01,WA,6519,Female,401483,Est Nunc Consulting,tent and awning shops,...,-13.3,23464.3,0.2,2120.0,48.0,121307174.0,47886.0,57220.0,NaN,NaN
1,11140,48248269920,0.928930,2022-04-01,VIC,3677,Male,813297,Etiam Bibendum Fermentum Institute,"digital goods: books, movies, music",...,10.6,57.6,345.2,10429.0,46.0,554992212.0,45587.0,53216.0,NaN,NaN
2,22286,71094934182,26.002530,2022-04-01,VIC,3172,Female,707121,Nonummy Ipsum Non LLC,tent And awning shops,...,-0.1,7.2,1457.0,6440.0,47.0,387504664.0,49812.0,60172.0,NaN,NaN
3,11141,89640578182,18.435005,2022-04-01,VIC,3202,Female,1027466,Magnis Foundation,tent and awning shops,...,9.9,11.7,786.2,5521.0,43.0,354869409.0,51528.0,64276.0,NaN,NaN
4,11141,24852446429,3.447834,2022-04-01,VIC,3202,Female,1027466,Erat Vitae LLP,"florists supplies, nursery stock, and floWers",...,9.9,11.7,786.2,5521.0,43.0,354869409.0,51528.0,64276.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3102071,24076,95896852636,62.756384,2022-08-28,VIC,3469,Male,435413,Rhoncus Associates,"computer proGramming , data processing, and in...",...,4.5,1714.2,2.0,1696.0,50.0,74282185.0,38543.0,43798.0,NaN,NaN
3102072,24077,80779820715,56.650642,2022-08-28,QLD,4474,Female,831103,Euismod Enim LLC,"watch, clock, and jewelry repair shops",...,-18.1,188751.6,0.0,1455.0,46.0,68532842.0,43303.0,47102.0,NaN,NaN
3102073,24080,89640578182,21.837852,2022-08-28,NSW,2809,Female,940951,Magnis Foundation,tent and awning shops,...,-4.4,3294.1,1.1,1852.0,51.0,94611201.0,41811.0,51086.0,NaN,NaN
3102074,24081,63290521567,19.628920,2022-08-28,VIC,3980,Female,1177416,Vehicula Pellentesque Corporation,artist supply and craft shops,...,4.9,98.5,82.0,4719.0,44.0,278635417.0,49975.0,59045.0,NaN,NaN
3102075,24081,68216911708,35.192603,2022-08-28,VIC,3980,Female,1177416,Placerat Eget Venenatis Limited,"computers, computer peripheral equipment, and ...",...,4.9,98.5,82.0,4719.0,44.0,278635417.0,49975.0,59045.0,NaN,NaN

In [5]:
consumer_fraud = pd.read_csv('../data/tables/consumer_fraud_probability.csv') 
merchant_fraud = pd.read_csv('../data/tables/merchant_fraud_probability.csv') 
consumer_fraud['order_datetime'] = pd.to_datetime(consumer_fraud['order_datetime'])
merchant_fraud['order_datetime'] = pd.to_datetime(merchant_fraud['order_datetime'])
consumer_fraud['user_id'] = consumer_fraud['user_id'].astype('str')
merchant_fraud['merchant_abn'] = merchant_fraud['merchant_abn'].astype('str')

In [6]:
consumer_fraud

      user_id order_datetime  fraud_probability
0        6228     2021-12-19          97.629808
1       21419     2021-12-10          99.247380
2        5606     2021-10-17          84.058250
3        3101     2021-04-17          91.421921
4       22239     2021-10-19          94.703425
...       ...            ...                ...
34859   18466     2022-02-22           8.679873
34860   17552     2021-12-26           8.349463
34861   17875     2021-06-27           8.288847
34862   10401     2021-09-18           8.842216
34863   18076     2021-11-30           8.542029

[34864 rows x 3 columns]

In [39]:
consumer_fraud.min()

user_id                                1
order_datetime       2021-02-28 00:00:00
fraud_probability               8.287144
dtype: object

In [49]:
consumer_fraud_20 = consumer_fraud[consumer_fraud["fraud_probability"] >= 20]

In [43]:
consumer_fraud_20

      user_id order_datetime  fraud_probability
0        6228     2021-12-19          97.629808
1       21419     2021-12-10          99.247380
2        5606     2021-10-17          84.058250
3        3101     2021-04-17          91.421921
4       22239     2021-10-19          94.703425
...       ...            ...                ...
10544   11017     2021-09-19          20.560891
10625     581     2021-10-12          20.008975
10685    4468     2022-01-10          20.642599
11112    5907     2021-04-20          20.327684
13335    9157     2021-11-29          20.916351

[5416 rows x 3 columns]

In [51]:
merchant_fraud

    merchant_abn order_datetime  fraud_probability
0    19492220327     2021-11-28          44.403659
1    31334588839     2021-10-02          42.755301
2    19492220327     2021-12-22          38.867790
3    82999039227     2021-12-19          94.134700
4    90918180829     2021-09-02          43.325517
..           ...            ...                ...
109  80089686333     2021-09-01          67.505811
110  83220249221     2021-11-27          63.512459
111  85482742429     2021-11-27          70.881311
112  11470993597     2021-09-28          63.377344
113  78080443264     2021-11-26          69.095317

[114 rows x 3 columns]

In [12]:
merchant_list = merchant_fraud['merchant_abn'].tolist()

In [13]:
merchant_list

['19492220327',
 '31334588839',
 '19492220327',
 '82999039227',
 '90918180829',
 '31334588839',
 '23686790459',
 '14827550074',
 '31334588839',
 '19492220327',
 '31334588839',
 '14827550074',
 '19492220327',
 '93260930990',
 '90918180829',
 '83199298021',
 '83199298021',
 '94311056026',
 '97217894162',
 '43083074133',
 '19492220327',
 '99989036621',
 '31334588839',
 '90918180829',
 '90918180829',
 '90918180829',
 '14827550074',
 '72058040180',
 '31334588839',
 '82368304209',
 '31334588839',
 '83199298021',
 '31334588839',
 '91880575299',
 '83199298021',
 '14827550074',
 '90918180829',
 '67264251405',
 '11590404675',
 '90568944804',
 '93260930990',
 '35575706403',
 '79827781481',
 '19010030815',
 '83199298021',
 '90918180829',
 '15043504837',
 '11149063370',
 '93260930990',
 '83199298021',
 '59258669983',
 '15043504837',
 '57564805948',
 '27093785141',
 '31334588839',
 '27093785141',
 '29674997261',
 '14530561097',
 '96680767841',
 '90568944804',
 '93558142492',
 '82368304209',
 '94493496784',
 '31334588839',
 '31334588839',
 '97884414539',
 '50315283629',
 '35909341340',
 '39649557865',
 '11149063370',
 '87084550311',
 '76767266140',
 '15043504837',
 '31334588839',
 '89109402284',
 '18158387243',
 '19492220327',
 '48534649627',
 '79827781481',
 '23709946765',
 '18158387243',
 '19010030815',
 '86889657711',
 '11149063370',
 '80518954462',
 '93260930990',
 '50315283629',
 '21439773999',
 '94311056026',
 '75892370170',
 '19492220327',
 '27093785141',
 '19010030815',
 '90568944804',
 '93260930990',
 '48534649627',
 '48534649627',
 '79100970961',
 '73052515151',
 '19492220327',
 '81146325646',
 '76968105359',
 '93292821052',
 '15157368385',
 '18737319630',
 '22606727520',
 '78187460332',
 '32258116290',
 '30275989942',
 '80089686333',
 '83220249221',
 '85482742429',
 '11470993597',
 '78080443264']

In [53]:
df3 = df

In [8]:
user_id_list = consumer_fraud['user_id'].tolist()

In [54]:
user_id_list_20 = consumer_fraud_20['user_id'].tolist()

In [26]:
type(user_id_list[0])

str

In [55]:
user_id_list = list(map(int, user_id_list))
merchant_list = list(map(int, merchant_list))
user_id_list_20 = list(map(int, user_id_list_20))

In [56]:
type(user_id_list_20[0])

int

In [30]:
type(merchant_list[0])

int

In [10]:
df2 = df

In [18]:
for i in merchant_list:
    df2.drop(df2[df2['merchant_abn']==i].index, inplace=True)

In [35]:
df

,user_id,merchant_abn,dollar_value,order_datetime,state,postcode,gender,consumer_id,name_y,tags,...,2011-2021%,Area,Population density 2021,Earners (persons)2017-18,Median age of earners (years)2017-18,Sum ($)2017-18,Median ($)2017-18,Mean ($)2017-18,fraud_probability_x,fraud_probability_y
0,11138,89726005175,47.782122,2022-04-01,WA,6519,Female,401483,Est Nunc Consulting,tent and awning shops,...,-13.3,23464.3,0.2,2120.0,48.0,121307174.0,47886.0,57220.0,NaN,NaN
1,11140,48248269920,0.928930,2022-04-01,VIC,3677,Male,813297,Etiam Bibendum Fermentum Institute,"digital goods: books, movies, music",...,10.6,57.6,345.2,10429.0,46.0,554992212.0,45587.0,53216.0,NaN,NaN
2,22286,71094934182,26.002530,2022-04-01,VIC,3172,Female,707121,Nonummy Ipsum Non LLC,tent And awning shops,...,-0.1,7.2,1457.0,6440.0,47.0,387504664.0,49812.0,60172.0,NaN,NaN
3,11141,89640578182,18.435005,2022-04-01,VIC,3202,Female,1027466,Magnis Foundation,tent and awning shops,...,9.9,11.7,786.2,5521.0,43.0,354869409.0,51528.0,64276.0,NaN,NaN
4,11141,24852446429,3.447834,2022-04-01,VIC,3202,Female,1027466,Erat Vitae LLP,"florists supplies, nursery stock, and floWers",...,9.9,11.7,786.2,5521.0,43.0,354869409.0,51528.0,64276.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3102071,24076,95896852636,62.756384,2022-08-28,VIC,3469,Male,435413,Rhoncus Associates,"computer proGramming , data processing, and in...",...,4.5,1714.2,2.0,1696.0,50.0,74282185.0,38543.0,43798.0,NaN,NaN
3102072,24077,80779820715,56.650642,2022-08-28,QLD,4474,Female,831103,Euismod Enim LLC,"watch, clock, and jewelry repair shops",...,-18.1,188751.6,0.0,1455.0,46.0,68532842.0,43303.0,47102.0,NaN,NaN
3102073,24080,89640578182,21.837852,2022-08-28,NSW,2809,Female,940951,Magnis Foundation,tent and awning shops,...,-4.4,3294.1,1.1,1852.0,51.0,94611201.0,41811.0,51086.0,NaN,NaN
3102074,24081,63290521567,19.628920,2022-08-28,VIC,3980,Female,1177416,Vehicula Pellentesque Corporation,artist supply and craft shops,...,4.9,98.5,82.0,4719.0,44.0,278635417.0,49975.0,59045.0,NaN,NaN
3102075,24081,68216911708,35.192603,2022-08-28,VIC,3980,Female,1177416,Placerat Eget Venenatis Limited,"computers, computer peripheral equipment, and ...",...,4.9,98.5,82.0,4719.0,44.0,278635417.0,49975.0,59045.0,NaN,NaN

In [23]:
df2.dtypes

user_id                                   int64
merchant_abn                              int64
dollar_value                            float64
order_datetime                           object
state                                    object
postcode                                  int64
gender                                   object
consumer_id                               int64
name_y                                   object
tags                                     object
revenue_levels                           object
take_rate                               float64
SA2 code                                float64
2021                                    float64
2011-2021\t                             float64
2011-2021%                              float64
Area                                    float64
Population density 2021                 float64
Earners (persons)2017-18                float64
Median age of earners (years)2017-18    float64
Sum ($)2017-18                          float64
Median ($)2017-18                       float64
Mean ($)2017-18                         float64
fraud_probability_x                     float64
fraud_probability_y                     float64
dtype: object

In [31]:
df2 = df2[~df2['user_id'].isin(user_id_list)]

In [57]:
df3 = df3[~df3['user_id'].isin(user_id_list_20)]

In [58]:
df3

,user_id,merchant_abn,dollar_value,order_datetime,state,postcode,gender,consumer_id,name_y,tags,...,2011-2021%,Area,Population density 2021,Earners (persons)2017-18,Median age of earners (years)2017-18,Sum ($)2017-18,Median ($)2017-18,Mean ($)2017-18,fraud_probability_x,fraud_probability_y
0,11138,89726005175,47.782122,2022-04-01,WA,6519,Female,401483,Est Nunc Consulting,tent and awning shops,...,-13.3,23464.3,0.2,2120.0,48.0,121307174.0,47886.0,57220.0,NaN,NaN
1,11140,48248269920,0.928930,2022-04-01,VIC,3677,Male,813297,Etiam Bibendum Fermentum Institute,"digital goods: books, movies, music",...,10.6,57.6,345.2,10429.0,46.0,554992212.0,45587.0,53216.0,NaN,NaN
2,22286,71094934182,26.002530,2022-04-01,VIC,3172,Female,707121,Nonummy Ipsum Non LLC,tent And awning shops,...,-0.1,7.2,1457.0,6440.0,47.0,387504664.0,49812.0,60172.0,NaN,NaN
3,11141,89640578182,18.435005,2022-04-01,VIC,3202,Female,1027466,Magnis Foundation,tent and awning shops,...,9.9,11.7,786.2,5521.0,43.0,354869409.0,51528.0,64276.0,NaN,NaN
4,11141,24852446429,3.447834,2022-04-01,VIC,3202,Female,1027466,Erat Vitae LLP,"florists supplies, nursery stock, and floWers",...,9.9,11.7,786.2,5521.0,43.0,354869409.0,51528.0,64276.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3102071,24076,95896852636,62.756384,2022-08-28,VIC,3469,Male,435413,Rhoncus Associates,"computer proGramming , data processing, and in...",...,4.5,1714.2,2.0,1696.0,50.0,74282185.0,38543.0,43798.0,NaN,NaN
3102072,24077,80779820715,56.650642,2022-08-28,QLD,4474,Female,831103,Euismod Enim LLC,"watch, clock, and jewelry repair shops",...,-18.1,188751.6,0.0,1455.0,46.0,68532842.0,43303.0,47102.0,NaN,NaN
3102073,24080,89640578182,21.837852,2022-08-28,NSW,2809,Female,940951,Magnis Foundation,tent and awning shops,...,-4.4,3294.1,1.1,1852.0,51.0,94611201.0,41811.0,51086.0,NaN,NaN
3102074,24081,63290521567,19.628920,2022-08-28,VIC,3980,Female,1177416,Vehicula Pellentesque Corporation,artist supply and craft shops,...,4.9,98.5,82.0,4719.0,44.0,278635417.0,49975.0,59045.0,NaN,NaN
3102075,24081,68216911708,35.192603,2022-08-28,VIC,3980,Female,1177416,Placerat Eget Venenatis Limited,"computers, computer peripheral equipment, and ...",...,4.9,98.5,82.0,4719.0,44.0,278635417.0,49975.0,59045.0,NaN,NaN

In [32]:
df2

,user_id,merchant_abn,dollar_value,order_datetime,state,postcode,gender,consumer_id,name_y,tags,...,2011-2021%,Area,Population density 2021,Earners (persons)2017-18,Median age of earners (years)2017-18,Sum ($)2017-18,Median ($)2017-18,Mean ($)2017-18,fraud_probability_x,fraud_probability_y
8,22291,64203420245,10.447550,2022-04-01,VIC,3159,Female,406308,Pede Nonummy Corp.,tent and awning shops,...,-3.1,55.7,181.4,6191.0,44.0,395846396.0,51296.0,63939.0,NaN,NaN
17,11146,94493496784,78.926294,2022-04-01,WA,6532,Male,1238525,Dictum Phasellus In Institute,"gift, card, novelty, and souvenir shops",...,-1.1,26161.9,0.2,3227.0,50.0,181786929.0,40598.0,56333.0,NaN,NaN
19,11146,19933438190,9.338781,2022-04-01,WA,6532,Male,1238525,Dui Nec Corporation,tent and awning shops,...,-1.1,26161.9,0.2,3227.0,50.0,181786929.0,40598.0,56333.0,NaN,NaN
23,22301,87457891433,41.710616,2022-04-01,WA,6351,Undisclosed,1195567,Magna Sed Incorporated,artist supply and craft shoPs,...,-7.4,28626.2,0.2,2967.0,46.0,218436784.0,57165.0,73622.0,NaN,NaN
24,11148,71528203369,7.960986,2022-04-01,NSW,2646,Female,285057,Ipsum Primis Associates,"watch, clock, and jewelry repair shops",...,7.5,4495.2,1.6,3763.0,49.0,183502253.0,42112.0,48765.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3102051,24055,79417999332,72.730216,2022-08-28,QLD,4608,Male,1379674,Phasellus At Company,"gift, card, novelty, and souvenIr shops",...,0.2,4332.3,2.2,4031.0,48.0,164337558.0,36531.0,40768.0,NaN,NaN
3102060,24064,81572403264,36.966756,2022-08-28,QLD,4516,Male,1229346,Interdum Curabitur Company,"digital goods: books, movies, music",...,14.1,101.2,43.0,2525.0,44.0,137312885.0,46865.0,54381.0,NaN,NaN
3102061,24064,19933438190,2.382190,2022-08-28,QLD,4516,Male,1229346,Dui Nec Corporation,tent and awning shops,...,14.1,101.2,43.0,2525.0,44.0,137312885.0,46865.0,54381.0,NaN,NaN
3102072,24077,80779820715,56.650642,2022-08-28,QLD,4474,Female,831103,Euismod Enim LLC,"watch, clock, and jewelry repair shops",...,-18.1,188751.6,0.0,1455.0,46.0,68532842.0,43303.0,47102.0,NaN,NaN
3102073,24080,89640578182,21.837852,2022-08-28,NSW,2809,Female,940951,Magnis Foundation,tent and awning shops,...,-4.4,3294.1,1.1,1852.0,51.0,94611201.0,41811.0,51086.0,NaN,NaN

In [59]:
df3 = df3[~df3['merchant_abn'].isin(merchant_list)]

In [60]:
df3

,user_id,merchant_abn,dollar_value,order_datetime,state,postcode,gender,consumer_id,name_y,tags,...,2011-2021%,Area,Population density 2021,Earners (persons)2017-18,Median age of earners (years)2017-18,Sum ($)2017-18,Median ($)2017-18,Mean ($)2017-18,fraud_probability_x,fraud_probability_y
0,11138,89726005175,47.782122,2022-04-01,WA,6519,Female,401483,Est Nunc Consulting,tent and awning shops,...,-13.3,23464.3,0.2,2120.0,48.0,121307174.0,47886.0,57220.0,NaN,NaN
1,11140,48248269920,0.928930,2022-04-01,VIC,3677,Male,813297,Etiam Bibendum Fermentum Institute,"digital goods: books, movies, music",...,10.6,57.6,345.2,10429.0,46.0,554992212.0,45587.0,53216.0,NaN,NaN
2,22286,71094934182,26.002530,2022-04-01,VIC,3172,Female,707121,Nonummy Ipsum Non LLC,tent And awning shops,...,-0.1,7.2,1457.0,6440.0,47.0,387504664.0,49812.0,60172.0,NaN,NaN
3,11141,89640578182,18.435005,2022-04-01,VIC,3202,Female,1027466,Magnis Foundation,tent and awning shops,...,9.9,11.7,786.2,5521.0,43.0,354869409.0,51528.0,64276.0,NaN,NaN
4,11141,24852446429,3.447834,2022-04-01,VIC,3202,Female,1027466,Erat Vitae LLP,"florists supplies, nursery stock, and floWers",...,9.9,11.7,786.2,5521.0,43.0,354869409.0,51528.0,64276.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3102071,24076,95896852636,62.756384,2022-08-28,VIC,3469,Male,435413,Rhoncus Associates,"computer proGramming , data processing, and in...",...,4.5,1714.2,2.0,1696.0,50.0,74282185.0,38543.0,43798.0,NaN,NaN
3102072,24077,80779820715,56.650642,2022-08-28,QLD,4474,Female,831103,Euismod Enim LLC,"watch, clock, and jewelry repair shops",...,-18.1,188751.6,0.0,1455.0,46.0,68532842.0,43303.0,47102.0,NaN,NaN
3102073,24080,89640578182,21.837852,2022-08-28,NSW,2809,Female,940951,Magnis Foundation,tent and awning shops,...,-4.4,3294.1,1.1,1852.0,51.0,94611201.0,41811.0,51086.0,NaN,NaN
3102074,24081,63290521567,19.628920,2022-08-28,VIC,3980,Female,1177416,Vehicula Pellentesque Corporation,artist supply and craft shops,...,4.9,98.5,82.0,4719.0,44.0,278635417.0,49975.0,59045.0,NaN,NaN
3102075,24081,68216911708,35.192603,2022-08-28,VIC,3980,Female,1177416,Placerat Eget Venenatis Limited,"computers, computer peripheral equipment, and ...",...,4.9,98.5,82.0,4719.0,44.0,278635417.0,49975.0,59045.0,NaN,NaN

In [34]:
df2

,user_id,merchant_abn,dollar_value,order_datetime,state,postcode,gender,consumer_id,name_y,tags,...,2011-2021%,Area,Population density 2021,Earners (persons)2017-18,Median age of earners (years)2017-18,Sum ($)2017-18,Median ($)2017-18,Mean ($)2017-18,fraud_probability_x,fraud_probability_y
8,22291,64203420245,10.447550,2022-04-01,VIC,3159,Female,406308,Pede Nonummy Corp.,tent and awning shops,...,-3.1,55.7,181.4,6191.0,44.0,395846396.0,51296.0,63939.0,NaN,NaN
19,11146,19933438190,9.338781,2022-04-01,WA,6532,Male,1238525,Dui Nec Corporation,tent and awning shops,...,-1.1,26161.9,0.2,3227.0,50.0,181786929.0,40598.0,56333.0,NaN,NaN
23,22301,87457891433,41.710616,2022-04-01,WA,6351,Undisclosed,1195567,Magna Sed Incorporated,artist supply and craft shoPs,...,-7.4,28626.2,0.2,2967.0,46.0,218436784.0,57165.0,73622.0,NaN,NaN
24,11148,71528203369,7.960986,2022-04-01,NSW,2646,Female,285057,Ipsum Primis Associates,"watch, clock, and jewelry repair shops",...,7.5,4495.2,1.6,3763.0,49.0,183502253.0,42112.0,48765.0,NaN,NaN
25,22301,16644129035,31.736720,2022-04-01,WA,6351,Undisclosed,1195567,Magna Associates,artist supply anD craft shops,...,-7.4,28626.2,0.2,2967.0,46.0,218436784.0,57165.0,73622.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3102051,24055,79417999332,72.730216,2022-08-28,QLD,4608,Male,1379674,Phasellus At Company,"gift, card, novelty, and souvenIr shops",...,0.2,4332.3,2.2,4031.0,48.0,164337558.0,36531.0,40768.0,NaN,NaN
3102060,24064,81572403264,36.966756,2022-08-28,QLD,4516,Male,1229346,Interdum Curabitur Company,"digital goods: books, movies, music",...,14.1,101.2,43.0,2525.0,44.0,137312885.0,46865.0,54381.0,NaN,NaN
3102061,24064,19933438190,2.382190,2022-08-28,QLD,4516,Male,1229346,Dui Nec Corporation,tent and awning shops,...,14.1,101.2,43.0,2525.0,44.0,137312885.0,46865.0,54381.0,NaN,NaN
3102072,24077,80779820715,56.650642,2022-08-28,QLD,4474,Female,831103,Euismod Enim LLC,"watch, clock, and jewelry repair shops",...,-18.1,188751.6,0.0,1455.0,46.0,68532842.0,43303.0,47102.0,NaN,NaN
3102073,24080,89640578182,21.837852,2022-08-28,NSW,2809,Female,940951,Magnis Foundation,tent and awning shops,...,-4.4,3294.1,1.1,1852.0,51.0,94611201.0,41811.0,51086.0,NaN,NaN

In [61]:
df2.to_parquet("../data/curated/data_half_year_deleted.parquet")